# Generated by Django 3.1.2 on 2020-11-01 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameZH', models.CharField(max_length=500)),
                ('nameEN', models.CharField(max_length=200)),
                ('addressZH', models.CharField(max_length=500)),
                ('addressEN', models.CharField(max_length=500)),
                ('x', models.DecimalField(decimal_places=0, max_digits=20)),
                ('y', models.DecimalField(decimal_places=0, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameZH', models.CharField(max_length=500)),
                ('nameEN', models.CharField(max_length=200)),
                ('addressZH', models.CharField(max_length=500)),
                ('addressEN', models.CharField(max_length=500)),
                ('x', models.DecimalField(decimal_places=0, max_digits=20)),
                ('y', models.DecimalField(decimal_places=0, max_digits=20)),
            ],
        ),
    ]
